spring:
  datasource:
    url: jdbc:mysql://ustinterview.c11i5wogetf8.ap-south-1.rds.amazonaws.com:3306/ustinterview
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: iamkevin7
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true